// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc49YyFGoEGEI4BQXK7lGYGyqi072s3Rk',
    appId: '1:949426880918:web:af80ba8bef34377de1ddb7',
    messagingSenderId: '949426880918',
    projectId: 'saboteur-danielluna',
    authDomain: 'saboteur-danielluna.firebaseapp.com',
    storageBucket: 'saboteur-danielluna.firebasestorage.app',
    measurementId: 'G-TK8R6XL3Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3vgi2CCr7H6gKlWBZnzHJI1myXy-Dvc',
    appId: '1:949426880918:android:015652a15832c995e1ddb7',
    messagingSenderId: '949426880918',
    projectId: 'saboteur-danielluna',
    storageBucket: 'saboteur-danielluna.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc49YyFGoEGEI4BQXK7lGYGyqi072s3Rk',
    appId: '1:949426880918:web:270fc6fddfd10a94e1ddb7',
    messagingSenderId: '949426880918',
    projectId: 'saboteur-danielluna',
    authDomain: 'saboteur-danielluna.firebaseapp.com',
    storageBucket: 'saboteur-danielluna.firebasestorage.app',
    measurementId: 'G-6VXDR7ELHJ',
  );
}
